"""Comment Generator - format and deduplicate review comments for VCS posting."""

import hashlib
from dataclasses import dataclass

import structlog

from app.config import get_settings
from app.services.policy_engine import PolicyViolation
from app.services.review_engine import AIReviewFinding, ReviewResult

logger = structlog.get_logger()
settings = get_settings()


@dataclass
class FormattedComment:
    file_path: str
    line_start: int
    line_end: int
    severity: str
    category: str
    title: str
    body: str
    suggestion: str
    evidence: str
    content_hash: str


def _severity_emoji(severity: str) -> str:
    return {
        "BLOCKER": "\u26d4",
        "WARNING": "\u26a0\ufe0f",
        "INFO": "\u2139\ufe0f",
    }.get(severity, "\u2139\ufe0f")


def _format_comment_body(comment: FormattedComment) -> str:
    emoji = _severity_emoji(comment.severity)
    parts = [
        f"### {emoji} [{comment.severity}] {comment.title}",
        f"**Category:** {comment.category}",
        "",
        comment.body,
    ]

    if comment.evidence:
        parts.extend(["", "**Evidence:**", f"```\n{comment.evidence}\n```"])

    if comment.suggestion:
        parts.extend(["", "**Suggested Fix:**", comment.suggestion])

    parts.extend(["", "---", "*Generated by DiffMaster*"])

    return "\n".join(parts)


def _compute_hash(file_path: str, severity: str, title: str, line: int) -> str:
    key = f"{file_path}:{severity}:{title}:{line}"
    return hashlib.sha256(key.encode()).hexdigest()[:16]


def _finding_to_comment(finding: AIReviewFinding) -> FormattedComment:
    return FormattedComment(
        file_path=finding.file_path,
        line_start=finding.line_start,
        line_end=finding.line_end,
        severity=finding.severity,
        category=finding.category,
        title=finding.title,
        body=finding.body,
        suggestion=finding.suggestion,
        evidence=finding.evidence,
        content_hash=_compute_hash(
            finding.file_path, finding.severity, finding.title, finding.line_start
        ),
    )


def _violation_to_comment(violation: PolicyViolation) -> FormattedComment:
    return FormattedComment(
        file_path=violation.file_path,
        line_start=violation.line,
        line_end=violation.line,
        severity=violation.severity,
        category=violation.rule_type,
        title=f"Policy: {violation.rule_name}",
        body=violation.message,
        suggestion=violation.suggestion,
        evidence=violation.evidence,
        content_hash=_compute_hash(
            violation.file_path, violation.severity, violation.rule_name, violation.line
        ),
    )


def _should_include(comment: FormattedComment) -> bool:
    severity_order = {"BLOCKER": 0, "WARNING": 1, "INFO": 2}
    min_order = severity_order.get(settings.min_severity, 2)
    comment_order = severity_order.get(comment.severity, 2)

    if comment_order > min_order:
        return False

    is_style_only = comment.category == "maintainability" and comment.severity == "INFO"
    return not (settings.suppress_style_only and is_style_only)


def generate_comments(
    review_result: ReviewResult,
    existing_hashes: set[str] | None = None,
) -> list[FormattedComment]:
    """Convert review findings and policy violations into deduplicated, formatted comments."""
    existing_hashes = existing_hashes or set()
    all_comments: list[FormattedComment] = []

    for finding in review_result.findings:
        comment = _finding_to_comment(finding)
        all_comments.append(comment)

    for violation in review_result.policy_violations:
        comment = _violation_to_comment(violation)
        all_comments.append(comment)

    filtered = [c for c in all_comments if _should_include(c)]

    seen_hashes: set[str] = set()
    deduped: list[FormattedComment] = []
    for comment in filtered:
        if comment.content_hash in seen_hashes or comment.content_hash in existing_hashes:
            continue
        seen_hashes.add(comment.content_hash)
        deduped.append(comment)

    severity_order = {"BLOCKER": 0, "WARNING": 1, "INFO": 2}
    deduped.sort(key=lambda c: severity_order.get(c.severity, 2))

    if len(deduped) > settings.max_comments_per_pr:
        logger.info(
            "comments_capped",
            total=len(deduped),
            cap=settings.max_comments_per_pr,
        )
        deduped = deduped[: settings.max_comments_per_pr]

    return deduped


def generate_summary(comments: list[FormattedComment]) -> str:
    """Generate a PR-level summary comment."""
    blocker_count = sum(1 for c in comments if c.severity == "BLOCKER")
    warning_count = sum(1 for c in comments if c.severity == "WARNING")
    info_count = sum(1 for c in comments if c.severity == "INFO")

    parts = [
        "## DiffMaster Review Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| \u26d4 BLOCKER | {blocker_count} |",
        f"| \u26a0\ufe0f WARNING | {warning_count} |",
        f"| \u2139\ufe0f INFO | {info_count} |",
        "",
    ]

    if blocker_count > 0:
        parts.append(
            "**Action Required:** This PR has blocker-level issues "
            "that must be resolved before merge."
        )
        parts.append("")

    if comments:
        parts.append("### Findings")
        for c in comments[:10]:
            emoji = _severity_emoji(c.severity)
            parts.append(f"- {emoji} **{c.title}** ({c.file_path}:{c.line_start})")

        if len(comments) > 10:
            parts.append(f"- ... and {len(comments) - 10} more")

    parts.extend(["", "---", "*Automated review by DiffMaster*"])

    return "\n".join(parts)


def format_for_vcs(comment: FormattedComment) -> str:
    return _format_comment_body(comment)
